CRUDProfile/api/api/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

CRUDProfile/core/core/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

CRUDProfile/home/home/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

CRUDProfile/home/urls.py
from django.urls import path
from home import views

app_name = "home"

urlpatterns = [
    path('databaseindex/', views.DBindex.as_view(), name="databaseindex"),
    path('new/category/', views.NewCategory.as_view(), name="new_category"),
    path('delete/category/<int:pk>/', views.DeleteCategory.as_view(), name="delete_category"),
    path('update/category/<int:pk>/', views.UpdateCategory.as_view(), name="update_category"),
    path('detail/category/<int:pk>/', views.DetailCategory.as_view(), name="detail_category"),
    #Alumno
    path('alumnoindex/', views.AlumnoIndex.as_view(), name="alumnoindex"),
    path('delete/alumno/<str:pk>/', views.DeleteAlumno.as_view(), name="delete_alumno"),
    path('new/alumno/', views.NewAlumno.as_view(), name="new_alumno"),
    path('update/alumno/<str:pk>/', views.UpdateAlumno.as_view(), name="update_alumno"),
    path('detail/alumno/<str:str_pk>/', views.DetailAlumno.as_view(), name="detail_alumno"),
    path('dbv/', views.DatabaseView.as_view(), name='dbv'),
    path('', views.Index.as_view(), name='index'),
    #PaginaWeb
    path('home/', views.PaginaView.as_view(), name='paginav'),
]

CRUDProfile/plaestemp/urls.py
from django.contrib import admin
from django.urls import path, include

from home import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
]

CRUDProfile/api/models.py
from django.db import models

# Create your models here.

CRUDProfile/core/models.py
from django.db import models

# Create your models here.

CRUDProfile/home/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import date
# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=16, null=False, blank=False)
    age = models.IntegerField(default=0)
    weight = models.FloatField(default=1.0)
    status = models.BooleanField(default=True)
    timestamp = models.DateField(auto_now_add=True)
    date_update = models.DateField(auto_now=True)
    slug = models.SlugField(max_length=16)

    def __str__(self):
        return self.name

class Category(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=16)
    status = models.BooleanField(default=True)

    def __str__(self):
        return self.name

class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    prodcut_name = models.CharField(max_length=16)
    status = models.BooleanField(default=True)

    def __str__(self):
        return self.prodcut_name
    
#Modelo Alumno
class Alumno(models.Model):
    matricula = models.CharField(max_length=10)
    nombre = models.CharField(max_length=100)
    apellidoP = models.CharField(max_length=100, default='No hay apellido')
    apellidoM = models.CharField(max_length=100, default='No hay apellido')
    telefono = models.CharField(max_length=20)
    fecha_nacimiento = models.DateField(default=date.today)

    def __str__(self):
        return self.nombre

#Modelo Profesor
class Profesor(models.Model):
    nombre = models.CharField(max_length=80)
    apellidoP = models.CharField(max_length=100, default='No hay apellido')
    apellidoM = models.CharField(max_length=100, default='No hay apellido')
    telefono = models.CharField(max_length=12)
    fecha_nacimiento = models.DateField()
    codigo = models.CharField(max_length=15)

    def __str__(self):
        return self.nombre

#Modelo Carrera 
class Carrera(models.Model):
    nombre = models.CharField(max_length=200)
    codigo = models.CharField(max_length=15)

    def __str__(self):
        return self.nombre

CRUDProfile/home/forms.py
from django import forms
from .models import Category, Alumno

class UpdateCategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = [
            "user",
            "name",
            "status"
        ]

class NewCategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = [
            "user",
            "name",
            "status"
        ]

#Alumno
class NewAlumnoForm(forms.ModelForm):
    class Meta:
        model = Alumno
        fields = [
            "nombre",
            "apellidoP",
            "apellidoM",
            "telefono",
            "fecha_nacimiento",
            "matricula"
        ]

class UpdateAlumnoForm(forms.ModelForm):
    class Meta:
        model = Alumno
        fields = [
            "nombre",
            "apellidoP",
            "apellidoM",
            "telefono",
            "fecha_nacimiento",
            "matricula"
        ]

CRUDProfile/api/views.py
from django.shortcuts import render

# Create your views here.

CRUDProfile/core/views.py
from django.shortcuts import render

# Create your views here.

CRUDProfile/home/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.views import generic
from django.urls import reverse_lazy
from .models import Category, Alumno
from .forms import UpdateCategoryForm, NewCategoryForm, NewAlumnoForm, UpdateAlumnoForm

# Create your views here.

# def index(request):
#     return render(request, "home/index.html", {})

#Plantilla para Category
class DetailCategory(generic.View):
    template_name = "home/detail_category.html"
    context = {}

    def get(self, request, pk):
        self.context = {
            "category": Category.objects.get(pk=pk)
        }
        return render(request, self.template_name, self.context)

class UpdateCategory(generic.UpdateView):
    template_name = "home/update_category.html"
    model = Category
    form_class = UpdateCategoryForm
    success_url = reverse_lazy("home:databaseindex")


class DeleteCategory(generic.DeleteView):
    template_name = "home/delete_category.html"
    model = Category
    success_url = reverse_lazy("home:databaseindex")


class NewCategory(generic.CreateView):
    template_name = "home/new_category.html"
    model = Category
    form_class = NewCategoryForm
    success_url = reverse_lazy("home:databaseindex")

class DBindex(generic.View):
    template_name = "home/databaseindex.html"
    context = {}

    def get(self, request):
        self.context = {
            "categories": Category.objects.all()
        }
        return render(request, self.template_name, self.context)

#Plantilla para alumno
class DetailAlumno(generic.View):
    template_name = "home/detail_alumno.html"
    context = {}

    def get(self, request, str_pk):
        self.context = {
            "alumno": get_object_or_404(Alumno, matricula=str_pk)
        }
        return render(request, self.template_name, self.context)

class DeleteAlumno(generic.DeleteView):
    template_name = "home/delete_alumno.html"
    model = Alumno
    success_url = reverse_lazy("home:alumnoindex")

    def get_object(self, queryset=None):
        return get_object_or_404(Alumno, matricula=self.kwargs['pk'])
    
class NewAlumno(generic.CreateView):
    template_name = "home/new_alumno.html"
    model = Alumno
    form_class = NewAlumnoForm
    success_url = reverse_lazy("home:alumnoindex")

class UpdateAlumno(generic.UpdateView):
    template_name = "home/update_alumno.html"
    model = Alumno
    form_class = UpdateAlumnoForm
    success_url = reverse_lazy("home:alumnoindex")

    def get_object(self, queryset=None):
        return get_object_or_404(Alumno, matricula=self.kwargs['pk'])

class AlumnoIndex(generic.View):
    template_name = "home/alumnoindex.html"
    context = {}

    def get(self, request):
        self.context = {
            "alumnos": Alumno.objects.all()
        }
        return render(request, self.template_name, self.context)
    
class DatabaseView(generic.View):
    template_name = "base/dbv.html"
    context = {}

    def get(self,request):
        return render(request, self.template_name,self.context)
    
class Index(generic.View):
    template_name = "base/lobby.html"
    context = {}

    def get(self,request):
        return render(request, self.template_name,self.context)
    
#PaginaView
class PaginaView(generic.View):
    template_name = "home/paginaweb.html"
    context = {}

    def get(self,request):
        return render(request, self.template_name,self.context)
    

CRUDProfile/templates/base/dbv.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  </head>
  <body>
    <div class="container">
        <!-- NAV BAR -->
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
              <a class="navbar-brand" href="#">WayneDev</a>
              <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'home:databaseindex' %}">Inicio</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'home:new_category' %}">Nueva Categoria</a>
                  </li>
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                      Menu
                    </a>
                    <ul class="dropdown-menu">
                      <li><a class="dropdown-item" href="{% url 'home:alumnoindex' %}">Alumnos</a></li>
                      <li><a class="dropdown-item" href="#">Profesores</a></li>
                      <li><a class="dropdown-item" href="#">Carreras</a></li>
                      <li><a class="dropdown-item" href="#">Directores</a></li>
                      <li><hr class="dropdown-divider"></li>
                      <li><a class="dropdown-item" href="#">About</a></li>
                    </ul>
                  </li>
                  
                </ul>
                <form class="d-flex" role="search">
                  <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                  <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
              </div>
            </div>
          </nav>
        {% block content %}
        {% endblock content %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
  </body>
</html>

CRUDProfile/templates/base/lobby.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>WayneDev - About Mí</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background: linear-gradient(to bottom, #fff, #ddd); /* Degradado blanco a gris */
            color: #333;
            margin: 0;
            padding: 0;
        }

        header {
            background: linear-gradient(to bottom, #000, #333); /* Degradado negro a gris oscuro */
            display: flex;
            justify-content: space-between;
            align-items: center;
            padding: 20px;
            border-bottom: 2px solid #333;
        }

        nav ul {
            list-style-type: none;
            margin: 0;
            padding: 0;
        }

        nav ul li {
            display: inline;
            margin-left: 20px;
        }

        nav ul li a {
            text-decoration: none;
            color: #fff;
        }

        section {
            padding: 40px;
            background: linear-gradient(to bottom, #fff, #eee); /* Degradado blanco a gris claro */
            color: #333;
        }

        h1, h2, h3 {
            color: #000;
        }

        img {
            max-width: 100%;
            height: auto;
        }

        footer {
            text-align: center;
            padding: 20px;
            background: linear-gradient(to bottom, #000, #333); /* Degradado negro a gris oscuro */
            color: #fff;
        }

        /* Estilos para los enlaces de proyectos */
        ul li a {
            text-decoration: none;
            color: #007bff; /* Azul */
        }

        ul li a:hover {
            text-decoration: underline;
        }

        /* Estilos para el menú de proyectos */
        .dropdown {
            position: relative;
            display: inline-block;
        }

        .dropdown-content {
            display: none;
            position: absolute;
            background-color: #333;
            min-width: 160px;
            z-index: 1;
        }

        .dropdown-content a {
            color: #fff;
            padding: 12px 16px;
            text-decoration: none;
            display: block;
        }

        .dropdown-content a:hover {
            background-color: #000;
        }

        .dropdown:hover .dropdown-content {
            display: block;
        }

        /* Estilos para centrar la sección "About Mí" */
        .centered {
            text-align: center;
        }

        /* Estilos para la sección "Contáctame" al final */
        #contactame {
            background: linear-gradient(to bottom, #333, #000); /* Degradado gris oscuro a negro */
            color: #fff;
            padding: 40px;
        }
        
        /* Estilos para "WayneDev" */
        header h1 {
            color: #fff;
        }
    </style>
</head>
<body>
    <header>
        <h1>WayneDev</h1>
        <nav>
            <ul>
                <li><a href="#inicio">Inicio</a></li>
                <li><a href="#sobre-mi">About Mí</a></li>
                <li class="dropdown">
                    <a href="#" class="dropbtn">Proyectos</a>
                    <div class="dropdown-content">
                        <a href="{% url 'home:databaseindex' %}">Base de Datos</a>
                        <a href="{% url 'home:paginav' %}">Pagina Web</a>
                        <a href="#proyecto-3">Proyecto 3</a>
                    </div>
                </li>
                <li><a href="#contactame">Contáctame</a></li>
            </ul>
        </nav>
    </header>

    <section id="inicio" class="section">
        <!-- Contenido de la sección "Inicio" -->
    </section>

    <section id="sobre-mi" class="section centered">
        <h2>Ponce Duarte Jose de Jesus</h2>
        <img src="https://media.licdn.com/dms/image/C5603AQFmWHN7hKxblQ/profile-displayphoto-shrink_200_200/0/1659770448607?e=1701302400&v=beta&t=Shkfhl-xpKTtcGgb8YNTowX7rm839zMUp9pdxcS2DxQ" alt="">
        <p>Hola, soy estudiante de Desarrollo de Software Multiplataforma, soy comprometido y autodidacta, además de que cuento con conocimientos en Java, MySQL, phpMyAdmin, HTML5 entre otras aptitudes.

            Cuando tengo un objetivo por delante lucho por lograrlo y completarlo, gracias a mi perseverancia y rápido aprendizaje. Me gusta liderar equipos además de aprender de ellos, así como a enseñar a los colaboradores de mi equipo la meta común "EL ÉXITO".</p>
    </section>

    <section id="proyecto-1" class="section">
        <!-- Contenido de la sección "Proyecto 1" -->
    </section>

    <section id="proyecto-2" class="section">
        <!-- Contenido de la sección "Proyecto 2" -->
    </section>

    <section id="proyecto-3" class="section">
        <!-- Contenido de la sección "Proyecto 3" -->
    </section>

    <section id="contactame" class="section">
        <h2>Contacto</h2>
        <ul>
            <li>Facebook: <a href="https://www.facebook.com/0YisusCry0">https://www.facebook.com/0YisusCry0</a></li>
            <li>Teléfono: +526632080121</li>
            <li>LinkedIn: <a href="https://www.linkedin.com/in/josepd/">https://www.linkedin.com/in/josepd/</a></li>
            <li>GitLab: <a href="https://gitlab.com/0322103790">https://gitlab.com/0322103790</a></li>
            <li>Discord: 1094058841404088330</li>
        </ul>
    </section>

    <footer

CRUDProfile/templates/home/alumnoindex.html
{% extends 'base/dbv.html' %}
{% block title %} Alumnos {% endblock title %}

{% block content %}
    <a href="{% url 'home:new_alumno' %}" class="btn btn-outline-info">Nuevo Alumno</a>
    
    <table class="table table-striped">
        <thead>
            <th>Matricula</th>
            <th>Nombre</th>
            <th>ApellidoPaterno</th>
            <th>ApellidoMaterno</th>
            <th>Telefono</th>
            <th>ACTIONS</th>
        </thead>
        <tbody>
            {% for alumno in alumnos %}
                <tr>
                    <td>{{ alumno.matricula }}</td>
                    <td>{{ alumno.nombre }}</td>
                    <td>{{ alumno.apellidoP }}</td>
                    <td>{{ alumno.apellidoM }}</td>
                    <td>{{ alumno.telefono }}</td>
                    <td><a href="{% url 'home:detail_alumno' alumno.matricula %}" class="btn btn-outline-info">Detail</a></td>
                    <td><a href="{% url 'home:delete_alumno' alumno.matricula %}" class="btn btn-outline-danger">Delete</a></td>
                    <td><a href="{% url 'home:update_alumno' alumno.matricula %}" class="btn btn-outline-warning">Update</a></td>
                </tr>    
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}

CRUDProfile/templates/home/databaseindex.html
{% extends 'base/dbv.html' %}
{% block title %} Vista Inicio {% endblock title %}

{% block content %}
    <table class="table table-striped">
        <thead>
            <th>ID</th>
            <th>NAME</th>
            <th>USER</th>
            <th>STATUS</th>
            <th></th>
            <th>ACTIONS</th>
            <th></th>
        </thead>
        <tbody>
            {% for category in categories %}
                <tr>
                    <td>{{ category.id }}</td>
                    <td>{{ category.name }}</td>
                    <td>{{ category.user }}</td>
                    <td>{{ category.status }}</td>
                    <td><a href="{% url 'home:detail_category' category.id %}" class="btn btn-outline-info">Detail</a></td>
                    <td><a href="{% url 'home:update_category' category.id %}" class="btn btn-outline-warning">Update</a></td>
                    <td><a href="{% url 'home:delete_category' category.id %}" class="btn btn-outline-danger">Delete</a></td>
                </tr>    
            
            {% endfor %}
        </tbody>
    </table>
    
{% endblock content %}

CRUDProfile/templates/home/delete_alumno.html
{% extends 'base/dbv.html' %}

{% block title %}Borrar Alumno{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        ¿Realmente deseas eliminar al alumno?: {{ object }}?
        <a href="{% url 'home:alumnoindex' %}" class="btn btn-outline-info">Cancel</a>
        <button type="submit" class="btn btn-outline-danger">Delete</button>
    </form>
{% endblock content %}

CRUDProfile/templates/home/delete_category.html
{% extends 'base/dbv.html' %}

{% block title %}Delete Category View{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        ¿Realmente deseas Eliminar esta categoria: {{ object }}?
        <a href="{% url 'home:databaseindex' %}" class="btn btn-outline-info">Cancel</a>
        <button type="submit" class="btn btn-outline-danger">Delete</button>
    </form>
{% endblock content %}

CRUDProfile/templates/home/detail_alumno.html
{% extends 'base/dbv.html' %}
{% block title %}Detalles del Alumno{% endblock title %}

{% block content %}
<div class="accordion" id="accordionExample">
    <div class="accordion-item">
      <h2 class="accordion-header">
        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
            {{ alumno.nombre }}
        </button>
      </h2>
      <div id="collapseOne" class="accordion-collapse collapse show" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          El alumno fue creado por: <strong>{{ category.user }}</strong> It is shown by default, until the collapse plugin adds the appropriate classes that we use to style each element. These classes control the overall appearance, as well as the showing and hiding via CSS transitions. You can modify any of this with custom CSS or overriding our default variables. It's also worth noting that just about any HTML can go within the The status category is: <strong><code>{{ category.status }}</code></strong>, though the transition does limit overflow. <a href="{% url 'home:alumnoindex' %}" class="btn btn-link">back to index</a>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

CRUDProfile/templates/home/detail_category.html
{% extends 'base/dbv.html' %}
{% block title %}Detail Category View{% endblock title %}

{% block content %}
<div class="accordion" id="accordionExample">
    <div class="accordion-item">
      <h2 class="accordion-header">
        <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
            {{ category.name }}
        </button>
      </h2>
      <div id="collapseOne" class="accordion-collapse collapse show" data-bs-parent="#accordionExample">
        <div class="accordion-body">
          The Category was created by: <strong>{{ category.user }}</strong> It is shown by default, until the collapse plugin adds the appropriate classes that we use to style each element. These classes control the overall appearance, as well as the showing and hiding via CSS transitions. You can modify any of this with custom CSS or overriding our default variables. It's also worth noting that just about any HTML can go within the The status category is: <strong><code>{{ category.status }}</code></strong>, though the transition does limit overflow. <a href="{% url 'home:databaseindex' %}" class="btn btn-link">back to index</a>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

CRUDProfile/templates/home/new_alumno.html
{% extends 'base/dbv.html' %}

{% block title %}Nuevo Alumno{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form }}
        <a href="{% url 'home:alumnoindex' %}" class="btn btn-outline-info">Cancel</a>
        <button type="submit" class="btn btn-outline-success">Nuevo Alumno</button>
    </form>
{% endblock content %}

CRUDProfile/templates/home/new_category.html
{% extends 'base/dbv.html' %}

{% block title %}New Categroy View{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form }}
        <a href="{% url 'home:databaseindex' %}" class="btn btn-outline-info">Cancel</a>
        <button type="submit" class="btn btn-outline-success">New Category</button>
    </form>
{% endblock content %}

CRUDProfile/templates/home/update_alumno.html
{% extends 'base/dbv.html' %}

{% block title %}Actualizar Alumno{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form }}
        <a href="{% url 'home:alumnoindex' %}" class="btn btn-outline-info">Cancel</a>
        <button type="submit" class="btn btn-outline-warning">Actualizar</button>
    </form>
{% endblock content %}

CRUDProfile/templates/home/update_category.html
{% extends 'base/dbv.html' %}

{% block title %}Update CAtegroy View{% endblock title %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form }}
        <a href="{% url 'home:databaseindex' %}" class="btn btn-outline-info">Cancel</a>
        <button type="submit" class="btn btn-outline-warning">Update</button>
    </form>
{% endblock content %}