NFLApp/nfl_pr/core/urls.py
from django.urls import path
from core import views

app_name = "core"
urlpatterns = [
    
]

NFLApp/nfl_pr/home/urls.py
from django.urls import path
from home import views
from .views import (
    CityWithTeams, TeamStadium,
    CityTeams,
)

app_name = "home"
urlpatterns = [
   # Rutas para el modelo Equipo
   path('equipo/', views.TeamIndex.as_view(), name='equipoindex'),
   path('equipo/', views.EquipoIndex.as_view(), name="teamindex"),
   path('equipo/new/', views.NewEquipo.as_view(), name='equipo_new'),
   path('equipo/<int:pk>/', views.DetailEquipo.as_view(), name='equipo_detail'),
   path('equipo/<int:pk>/edit/', views.UpdateEquipo.as_view(), name='equipo_edit'),
   path('equipo/<int:pk>/delete/', views.DeleteEquipo.as_view(), name='equipo_delete'),

   # Rutas para el modelo Ciudad
   path('ciudad/', views.CityIndex.as_view(), name='ciudadindex'),
   path('ciudad/new/', views.NewCiudad.as_view(), name='ciudad_new'),
   path('ciudad/<int:pk>/', views.DetailCiudad.as_view(), name='ciudad_detail'),
   path('ciudad/<int:pk>/edit/', views.UpdateCiudad.as_view(), name='ciudad_edit'),
   path('ciudad/<int:pk>/delete/', views.DeleteCiudad.as_view(), name='ciudad_delete'),

   # Rutas para el modelo Ciudad
   path('estadio/', views.StadiumIndex.as_view(), name='estadioindex'),
   path('estadio/new/', views.NewEstadio.as_view(), name='estadio_new'),
   path('estadio/<int:pk>/', views.DetailEstadio.as_view(), name='estadio_detail'),
   path('estadio/<int:pk>/edit/', views.UpdateEstadio.as_view(), name='estadio_edit'),
   path('estadio/<int:pk>/delete/', views.DeleteEstadio.as_view(), name='estadio_delete'),

   # Ruta para la página de inicio
   path('', views.Index.as_view(), name='index'),

   #Consultas
   path('equipo/citywithteams/', CityWithTeams.as_view(), name='cityWithTeams'),
   path('equipo/teamstadium/', TeamStadium.as_view(), name='teamsStadium'),
   path('equipo/cityteams/', CityTeams.as_view(), name='cityTeams'),
]

NFLApp/nfl_pr/nfl_pr/urls.py
from django.contrib import admin
from django.urls import path, include
from home import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("home.urls")),
    path('core/', include("core.urls")),
]

NFLApp/nfl_pr/templates/base/equipoindex.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %}{% endblock title %}</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
<body>
  <div class="container">
    <!-- NAV BAR -->
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">TeamIndex</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'home:equipoindex' %}">Inicio</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'home:ciudadindex' %}">Ciudades</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'home:estadioindex' %}">Estadios</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Menu
              </a>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{% url 'home:cityWithTeams' %}">CiudadConEquipo</a></li>
                <li><a class="dropdown-item" href="{% url 'home:teamsStadium' %}">EquipoPorEstadio</a></li>
                <li><a class="dropdown-item" href="{% url 'home:cityTeams' %}">EquiposConCiudad</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="#">About</a></li>
              </ul>
            </li>
          </ul>
          <form class="d-flex" role="search">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
        </div>
      </div>
    </nav>
    {% block content %}
    {% endblock content %}
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
</body>
</html>

NFLApp/nfl_pr/templates/base/lobby.html
<!DOCTYPE html>
<html lang="es">
<head>
  <title>NFL</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #013369;">
    <a class="navbar-brand" href="#">NFL</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Acerca de nosotros</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Secciones
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="{% url 'home:equipoindex' %}">Equipos</a>
            <a class="dropdown-item" href="#">Sección 2</a>
            <a class="dropdown-item" href="#">Sección 3</a>
          </div>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#contacto">Contactos</a>
        </li>
      </ul>
    </div>
  </nav>
  <div class="container my-4">
    <h2>La NFL</h2>
    <p>La NFL (National Football League) es la mayor liga de fútbol americano profesional en los Estados Unidos. La NFL toma la figura de una asociación de sus 32 equipos y es la mayor liga deportiva del país.</p>
  </div>
  <footer class="footer bg-light text-left fixed-bottom p-4">
    <div class="container" id="contacto">
      <h2>Contacto</h2>
      <p><a href="https://www.linkedin.com">LinkedIn</a></p>
      <p><a href="https://discord.com">Discord</a></p>
      <p>Número de teléfono: (123) 456-7890</p>
      <p><a href="https://www.facebook.com">Facebook</a></p>
      <p><a href="https://gitlab.com">GitLab</a></p>
    </div>
  </footer>
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
</body>
</html>